# Generated by Django 5.1.4 on 2025-04-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet_Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_type', models.CharField(max_length=50)),
                ('pet_breed', models.CharField(max_length=50)),
                ('pet_age', models.IntegerField()),
                ('pet_months', models.CharField(max_length=50)),
                ('pet_gender', models.CharField(max_length=50)),
                ('pet_size', models.CharField(max_length=50)),
                ('pet_desc', models.TextField()),
                ('pet_photo', models.ImageField(upload_to='pet_photos')),
            ],
        ),
    ]
