# Generated by Django 5.1.4 on 2025-04-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_adoption',
            name='contact_city',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='pet_adoption',
            name='contact_email',
            field=models.EmailField(default='Unknown', max_length=254),
        ),
        migrations.AddField(
            model_name='pet_adoption',
            name='contact_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='pet_adoption',
            name='contact_phoneno',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
