# Generated by Django 5.1.4 on 2025-04-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_pet_adoption_contact_city_pet_adoption_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=40)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phoneno', models.CharField(max_length=10)),
                ('contact_subject', models.CharField(max_length=30)),
                ('contact_message', models.TextField()),
            ],
        ),
    ]
