# Generated by Django 5.1.4 on 2025-04-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_contact_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_adoption',
            name='pet_age_type',
            field=models.CharField(default='Young', max_length=30),
        ),
        migrations.AddField(
            model_name='pet_adoption',
            name='pet_color',
            field=models.CharField(default='White', max_length=30),
        ),
    ]
