# Generated by Django 5.1.4 on 2025-04-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_pet_adoption_pet_age_type_pet_adoption_pet_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_adoption',
            name='pet_background',
            field=models.TextField(default='No Information Available'),
        ),
    ]
