# Generated by Django 5.1.4 on 2025-04-13 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_add_to_favourites_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 13, 15, 4, 54, 626041, tzinfo=datetime.timezone.utc)),
        ),
    ]
