# Generated by Django 5.1.4 on 2025-04-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_notifications_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
