# Generated by Django 5.1.4 on 2025-04-13 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_notifications_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_adoption',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 13, 16, 6, 1, 872863, tzinfo=datetime.timezone.utc)),
        ),
    ]
