# Generated by Django 5.1.4 on 2025-04-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_pet_adoption_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_adoption',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
